layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "_posts/" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 12
  exclude:
    archived: true
    forks: true
    projects:
    - svrooij.github.io
    - node-sonos
    - svrooij

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: svrooij
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: stephanvanrooij
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 639153
  # telegram: your_username
  twitter: svrooij
  # unsplash: your_username
  # vk: your_username
  website: https://svrooij.io
  # youtube: your_username

topics:
  - name: Home Automation
    web_url: https://github.com/topics/homeautomation

  - name: MQTT
    web_url: https://github.com/topics/mqtt

  - name: ESP8266
    web_url: https://github.com/topics/esp8266

